Repository TrixiEther/Dashchan-Extensions, pull requests merged in 2024-09, with the labels that each got.

#85 DobrochanRefuge: markup support
  extensions/refugedobrochan/build.gradle
  extensions/refugedobrochan/src/com/trixiether/dashchan/chan/refugedobrochan/RefugeDobrochanChanMarkup.java
Labels: module

#83 Support emoji_captcha for 2ch.hk
  extensions/dvach/res/values-ru/strings.xml
  extensions/dvach/res/values/strings.xml
  extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachChanConfiguration.java
  extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachChanPerformer.java
  extensions/dvach/src/com/mishiranu/dashchan/chan/dvach/DvachEmojiCaptchaProvider.java
Labels: module

#86 Update build.gradle
  extensions/dvach/build.gradle
Labels: enhancement, module

#88 dvach emoji captcha dark theme support
  extensions/dvach/build.gradle
Labels: enhancement
