Repository TrixiEther/Dashchan-Extensions, pull requests merged in 2024-01, with the labels that each got.

#70 TrixiEther | Dobrochan Rf 1.4 fixes
  engines/vichan/src/chan/content/VichanChanMarkup.java
  engines/vichan/src/chan/content/VichanModelMapper.java
  extensions/refugedobrochan/build.gradle
  extensions/refugedobrochan/src/com/trixiether/dashchan/chan/refugedobrochan/RefugeDobrochanChanMarkup.java
Labels: bug

#71 fourchan: fix "Invalid server response" error when getting captcha
  extensions/fourchan/src/com/mishiranu/dashchan/chan/fourchan/FourchanChanLocator.java
Labels: bug, module

#72 fourchan: fix missing report option
  extensions/fourchan/src/com/mishiranu/dashchan/chan/fourchan/FourchanChanPerformer.java
Labels: bug, module

#73 TrixiEther | Fourchan - Remove Redundant Argument
  extensions/fourchan/src/com/mishiranu/dashchan/chan/fourchan/FourchanChanLocator.java
Labels: bug, module

#74 Dollchan: support for extra icons (“achievements”)
  extensions/dollchan/build.gradle
  extensions/dollchan/src/com/mishiranu/dashchan/chan/dollchan/DollchanPostsParser.java
Labels: module
